title: Vishnu Ponduri
logo: images/Vishnu_Ponduri(1).jpg
description: |
  MS in Business Analytics and Information Management, Purdue University
  M.Tech, Construction Technology and Management, NIT Trichy
logo_images:
  - name: Purdue Logo
    path: images/purdue.png
  - name: NIT Trichy Logo
    path: images/National_Institute_of_Technology_Trichy_Logo.png
theme: jekyll-theme-minimal
#show_downloads: true
