title: Vishnu Ponduri # your name (or website title) here
logo: "/images/dp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p align="center">
    Master of Science Business Analytics and Information Managment, Purdue
    <br>
    M.Tech, Construction Technology and Managment NIT Trichy
    <br><br>
    <img src="images/kisspng-computer-icons-linkedin-5aff0283e54964.1704227815266617639392.png" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/vishnuponduri/">vishnu_ponduri</a> 
    <br>
    <img src="images/kisspng-computer-icons-logo-portable-network-graphics-clip-icons-for-free-iconza-circle-social-5b7fe46b4ec817.2080142615351082033227.png" width="5%" height="5%"/>
    <a href="https://github.com/vishnuponduri1">vishnu-01</a> 
    <br>
    <br>
    <img src="images/National_Institute_of_Technology_Trichy_Logo.png" width="30%" height="30%"/>
    <img src="images/purdue.png" width="30%" height="30%"/>
  </p>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
